name: Frontend Image

on:
  push:
    branches:
      - "main"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Container Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/backend

      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.AWS_REMOTE_IP }}
          username: ${{ secrets.AWS_REMOTE_USER }}
          key: ${{ secrets.AWS_REMOTE_PRIVATE_KEY }}
          port: 22
          timeout: 40s
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/backend
            docker rm -f container-backend
            docker run -d -p 5000:5000 --name container-backend ${{ secrets.DOCKER_USERNAME }}/backend
